name: Generate Protobuf Code
on:
  push:
    branches: [main]
    paths:
      - 'sources/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install buf
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/latest/download/buf-$(uname -s)-$(uname -m)" -o "/tmp/buf"
          chmod +x "/tmp/buf"
          sudo mv "/tmp/buf" "/usr/local/bin/buf"

      - name: Generate code
        run: |
          buf mod update
          buf generate
          
      - name: Commit generated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add generated/
          git commit -m "Generated code from protos" || echo "No changes to commit"
          git push